export const NOW_LOADING = 'NOW_LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';
export const FETCH_ALL_FLAGS_REQUESTED = 'FETCH_ALL_FLAGS_REQUESTED';
export const FETCH_ALL_FLAGS_SUCCEEDED = 'FETCH_ALL_FLAGS_SUCCEEDED';
export const FETCH_ALL_FLAGS_FAILED = 'FETCH_ALL_FLAGS_FAILED';
export const DELETE_FLAG_REQUESTED = 'DELETE_FLAG_REQUESTED';
export const DELETE_FLAG_SUCCEEDED = 'DELETE_FLAG_SUCCEEDED';
export const DELETE_FLAG_FAILED = 'DELETE_FLAG_FAILED';
