export default {
  RECEIVED_SITES    : 'RECEIVED_SITES',
  RECEIVED_FLAGS    : 'RECEIVED_FLAGS',
  ADDED_SITE_FLAG   : 'ADDED_SITE_FLAG',
  REMOVED_SITE_FLAG : 'REMOVED_SITE_FLAG',
  UPDATED_SITE_FLAG : 'UPDATED_SITE_FLAG'
}
