export const EDIT_FLAG = 'EDIT_FLAG'
export const UPDATE_FLAG = 'UPDATE_FLAG'

export const ADD_FLAG = 'ADD_FLAG'
export const CREATE_FLAG = 'CREATE_FLAG'

export const CONFIRM_DELETE_FLAG = 'CONFIRM_DELETE_FLAG'

export const SITE_DATA_LOADING = 'SITE_DATA_LOADING'
export const SITE_DATA_RESPONSE = 'SITE_DATA_RESPONSE'

export const SITE_DATA_SAVE_SENDING = 'SITE_DATA_SAVE_SENDING'
export const SITE_DATA_SAVE_RESPONSE = 'SITE_DATA_SAVE_RESPONSE'

export const SITES_LIST_LOADING = 'SITES_LIST_LOADING'
export const SITES_LIST_RESPONSE = 'SITES_LIST_RESPONSE'

export const SELECT_SITE = 'SELECT_SITE'
export const UNSELECT_ACTIVE_SITE = 'UNSELECT_ACTIVE_SITE'

